---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install MySQL
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present

- name: Enable mysql
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: started

- name: Allow remote connections
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart mysql

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create application user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Flush privileges
  community.mysql.mysql_query:
    query: FLUSH PRIVILEGES;
    login_unix_socket: /var/run/mysqld/mysqld.sock