---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
      - unzip
      - curl
    state: present
    update_cache: true

- name: Download AWS CLI v2
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: "0644"

- name: Extract AWS CLI
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true

- name: Install AWS CLI
  ansible.builtin.command:
    cmd: /tmp/aws/install --update

- name: Verify credentials
  command:
    argv:
      - aws 
      - sts 
      - get-caller-identity 
      - --region 
      - "{{ aws_region }}"

- name: Read database secret
  command:
    argv:
      - aws
      - secretsmanager
      - get-secret-value
      - --secret-id
      - "{{ db_secret_name }}"
      - --region
      - "{{ aws_region }}"
  register: secret_json

- name: Parse AWS response
  ansible.builtin.set_fact:
    secret: "{{ secret_json.stdout | from_json }}"

- name: Parse SecretString
  ansible.builtin.set_fact:
    db_credentials: "{{ secret.SecretString | from_json }}"
  
- name: Set database variables
  ansible.builtin.set_fact:
    # db_port: "{{ db_credentials.db_port }}"
    db_name: "{{ db_credentials.db_name }}"
    db_username: "{{ db_credentials.db_username }}"
    db_password: "{{ db_credentials.db_password }}"

- name: Debug ead database secret
  ansible.builtin.debug:
    msg:
    - "db_name: {{ db_name }}"
    - "db_username: {{ db_username }}"
    - "db_password: {{ db_password }}"

- name: Enable mysql
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: started

- name: Allow remote connections
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart mysql

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create application user
  community.mysql.mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Flush privileges
  community.mysql.mysql_query:
    query: FLUSH PRIVILEGES;
    login_unix_socket: /var/run/mysqld/mysqld.sock