---
- hosts: frontend
  become: true

  roles:
    - role: frontend
      tags:
        - frontend

# - hosts: backend
#   become: true

#   roles:
#     - role: backend
#       tags:
#         - backend

# - hosts: db
#   become: true

#   roles:
#     - role: db
#       tags:
#         - db